# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build Firstjob
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: echo ls -R $(System.DefaultWorkingDirectory)
    - bash: echo mvn -version
    - bash: java -version
    - bash: node --version
    - bash: python --version
    - bash: mvn -version
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
# - stage: DevDeploy
#   dependsOn: Build
#   jobs:
#   - job: FirstDevJob
#     steps:
#     - bash: echo Build FirstDevjob
#   - job: SecondDevJob
#     steps:
#     - bash: echo Build SecondDevJob
# - stage: QADeploy
#   dependsOn: Build
#   jobs:
#   - job: FirstQAJob
#     steps:
#     - bash: echo Build FirstQAjob
#   - job: SecondQAJob
#     steps:
#     - bash: echo Build SecondQAJob
# - stage: ProdDeploy
#   dependsOn: 
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: FirstProdJob
#     steps:
#     - bash: echo Build FirstProdjob
#   - job: SecondProdJob
#     steps:
#     - bash: echo Build SecondProdJob