# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build Firstjob
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: echo ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
# - stage: DevDeploy
#   dependsOn: Build
#   jobs:
#   - job: FirstDevJob
#     steps:
#     - bash: echo Build FirstDevjob
#   - job: SecondDevJob
#     steps:
#     - bash: echo Build SecondDevJob
# - stage: QADeploy
#   dependsOn: Build
#   jobs:
#   - job: FirstQAJob
#     steps:
#     - bash: echo Build FirstQAjob
#   - job: SecondQAJob
#     steps:
#     - bash: echo Build SecondQAJob
# - stage: ProdDeploy
#   dependsOn: 
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: FirstProdJob
#     steps:
#     - bash: echo Build FirstProdjob
#   - job: SecondProdJob
#     steps:
#     - bash: echo Build SecondProdJob