version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: users_dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

    ports:
      - "3306:3306"
    networks:
      - app-mysql-network  
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    
  user-service:
    restart: on-failure
    build: ./
    image: ashoknautiyal/user-service-docker-image
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
    networks:
      - app-mysql-network  
 
networks:
   app-mysql-network:   